### ISSUE TITLE
"An error occured, the information is:" happens when I start watching the video

### ISSUE THREAD

**Issue by WF4123** [lightbeam24/StarTube#20]
![Image](https://github.com/user-attachments/assets/0ab4e9d0-88eb-4378-b671-085aa6265742)

My browser is Supermium v1.26 and this happens. This issues cannot be solved for me with StarTube

**Comment by Ksmith2003** [comment]
im getting this error too on microsoft edge

**Comment by SubjectULTIMA** [comment]
Same with firefox

**Comment by AyeTSG** [comment]
Likewise here, running latest Firefox.

**Comment by lightbeam24** [comment]
Not a StarTube issue, it's an issue with V3 that should be fixed soon.

**Comment by lightbeam24** [comment]
Oh right, in the meantime, you can use the embed player to fix it:
![Image](https://github.com/user-attachments/assets/9ec2ee82-75e0-45ac-8d8e-122878db626f)

**Comment by AyeTSG** [comment]
> Oh right, in the meantime, you can use the embed player to fix it: ![Image](https://github.com/user-attachments/assets/9ec2ee82-75e0-45ac-8d8e-122878db626f)

It appears the latest V3 update still has not fixed the issue. However, the embed player does work in the meantime for 90% of videos on the website. However, videos with embeds disabled will refuse to play at all

**Comment by artenax** [comment]
Or you can use [External Application Launcher](https://chromewebstore.google.com/detail/external-application-laun/bifmfjgpgndemajpeeoiopbeilbaifdo) (it requires [NodeJS](https://nodejs.org/en/download)) and send links to mpv+yt-dlp.
The downside is that mpv takes a long time to start up, but it consumes less CPU resources and supports all the sites that yt-dlp supports.
